/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package singleton.ventanas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.awt.image.ImageObserver.WIDTH;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.WindowConstants;

/**
 *
 * @author steve
 */
public class VentanaEventos extends javax.swing.JFrame {

    /**
     * Creates new form VentanaEventos
     */
    private String persona;
    private static VentanaLog ventanaLogs;
    private String texto;
    public VentanaEventos(String persona) {
        initComponents();
        this.persona=persona;
      userSelect.setText(  userSelect.getText()+ ":" + this.persona );
        openEnvent(envento1);
        openEnvent(envento2);
        openEnvent(evento3);
        openEnvent(envento4);
        openEnvent(envento5);
        openEnvent(envento6);
        openEnvent(envento7);
        openEnvent(envento8);
        openEnvent(envento9);
        ventanaLogs = new VentanaLog();
        
      
    }

    
   private void openEnvent(JButton btn){
        
 
     
      btn.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                
         
                 ventanaLogs.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
               if(!ventanaLogs.isVisible()){
                    ventanaLogs.setVisible(true);
               }         
                   ventanaLogs.SetTexto(new Date() + " - "+persona  + " " + btn.getText());
           
            }
        });
      
    }
   
    
 
   /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        userSelect = new javax.swing.JLabel();
        envento1 = new javax.swing.JButton();
        envento8 = new javax.swing.JButton();
        envento2 = new javax.swing.JButton();
        envento5 = new javax.swing.JButton();
        envento4 = new javax.swing.JButton();
        envento7 = new javax.swing.JButton();
        evento3 = new javax.swing.JButton();
        envento6 = new javax.swing.JButton();
        envento9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Visor De Eventos");

        userSelect.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        userSelect.setText("User: ");

        envento1.setText("Evento 1");
        envento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                envento1ActionPerformed(evt);
            }
        });

        envento8.setText("Evento 8");
        envento8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                envento8ActionPerformed(evt);
            }
        });

        envento2.setText("Evento 2");
        envento2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                envento2ActionPerformed(evt);
            }
        });

        envento5.setText("Evento 5");
        envento5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                envento5ActionPerformed(evt);
            }
        });

        envento4.setText("Evento 4");
        envento4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                envento4ActionPerformed(evt);
            }
        });

        envento7.setText("Evento 7");
        envento7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                envento7ActionPerformed(evt);
            }
        });

        evento3.setText("Evento 3");
        evento3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evento3ActionPerformed(evt);
            }
        });

        envento6.setText("Evento 5");
        envento6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                envento6ActionPerformed(evt);
            }
        });

        envento9.setText("Evento 9");
        envento9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                envento9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(userSelect))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(envento1)
                                    .addComponent(envento4))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(envento5)
                                        .addGap(18, 18, 18)
                                        .addComponent(envento6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(envento2)
                                        .addGap(18, 18, 18)
                                        .addComponent(evento3))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(envento7)
                                .addGap(29, 29, 29)
                                .addComponent(envento8)
                                .addGap(18, 18, 18)
                                .addComponent(envento9)))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(userSelect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(envento1)
                    .addComponent(envento2)
                    .addComponent(evento3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(envento4)
                    .addComponent(envento5)
                    .addComponent(envento6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(envento7)
                    .addComponent(envento8)
                    .addComponent(envento9))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void envento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_envento1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_envento1ActionPerformed

    private void envento8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_envento8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_envento8ActionPerformed

    private void envento2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_envento2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_envento2ActionPerformed

    private void envento5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_envento5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_envento5ActionPerformed

    private void envento4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_envento4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_envento4ActionPerformed

    private void envento7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_envento7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_envento7ActionPerformed

    private void evento3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evento3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_evento3ActionPerformed

    private void envento6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_envento6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_envento6ActionPerformed

    private void envento9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_envento9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_envento9ActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton envento1;
    private javax.swing.JButton envento2;
    private javax.swing.JButton envento4;
    private javax.swing.JButton envento5;
    private javax.swing.JButton envento6;
    private javax.swing.JButton envento7;
    private javax.swing.JButton envento8;
    private javax.swing.JButton envento9;
    private javax.swing.JButton evento3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel userSelect;
    // End of variables declaration//GEN-END:variables
}
